WIP : Create App
platformercloud/cli pull request #32
Opened 2021-04-21 12:12 UTC by sithumonline

2021-04-23 04:00 UTC, ChathurangaKCD requested changes

2021-04-23 04:00 UTC, ChathurangaKCD commented on src/commands/app/env.ts
> +    cli.action.stop('\nConfigured environment for app');
Should be `cli.action.start` , also need to change the message.

2021-04-23 04:00 UTC, ChathurangaKCD commented on src/commands/app/con.ts
> +      cpu: flags.cpu,
should be validated for min/max

2021-04-23 04:00 UTC, ChathurangaKCD commented on src/commands/app/con.ts
> +      port: flags.port
multiple ports?, also needs to be disabled for `INIT` type

2021-04-23 04:00 UTC, ChathurangaKCD commented on src/commands/app/env.ts
> +      description: 'Service Type (ClusterIP|NodePort|LoadBalancer)',
need to validate enum

2021-04-29 15:40 UTC, Shehanka approved these changes

2021-05-06 04:11 UTC, ChathurangaKCD commented on src/commands/app/env.ts
> +    const appName = getDefaultAppName();
reads the file 3 times.
define an interface for file data, & read once.

2021-05-06 04:18 UTC, ChathurangaKCD commented on src/modules/apps/files.ts
> +    json = JSON.parse(data);
```suggestion
    return JSON.parse(data);
```

2021-05-10 03:23 UTC, ChathurangaKCD requested changes

2021-05-10 03:23 UTC, ChathurangaKCD commented on src/modules/util/validations.ts
> +  let envId;
```suggestion
  const envId = (await getEnvironmentIdByName(organizationId, projectId, environmentName)).
    ?.ID;
```

2021-05-10 03:23 UTC, ChathurangaKCD commented on src/commands/app/env.ts
> +    await ensureTargetNamespace({ orgId: fileData.orgId, projectId: fileData.projectId, envId, name: flags.namespace });
shouldn't create a namespace, if it doesn't exist

2021-05-10 03:23 UTC, ChathurangaKCD commented on src/modules/apps/files.ts
> +export function writeFile(content: any) {
```suggestion
export function writeFile(content: AppCreate) {
```

2021-05-11 08:33 UTC, merged